# Site
name: "CookieCode"
title: "CookieCode"
description: "CookieCode"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: "https://cookiecode.dev"

# comment when publish to git
#baseurl: "/cookie"
google_analytics: 'UA-91985102-2'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: "/:categories/:title:output_ext"

# Authors
authors:
  sbeex:
    name: Sebastien Vermeille
    display_name: sbeex
    gravatar: db2e260f57e40ade7907bc303a295b70
    email: sebastien.vermeille@gmail.com
    web: https://cookiecode.dev/
    description: "Author of CookieCode, Clean Code principles supporter."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji
  - premonition

gems: []
#emoji:
# used to define a custom set of emojis
#  src: "/assets/images/emoji"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - month
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'source-code'
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

collections:
  oss:
    output: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

sass:
  sass_dir: _sass
  style: compressed

premonition:
  types:
    error:
      fa-icon: "fa-bug"
    question:
      fa-icon: "fa-question"

