# Site
name: "CookieCode"
title: "CookieCode"
tagline: A blog dedicated to programming world
description: "In this blog I share with you some answers to problems I faced during my life of developer. Also some nice tools I like to use, configurations and so on."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: "https://cookiecode.dev"
locale: 'en_US'
# comment when publish to git
#baseurl: "/cookie"
google_analytics: 'UA-91985102-2'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: "/:categories/:title:output_ext"

# Authors
authors:
  sbeex:
    name: Sebastien Vermeille
    display_name: sbeex
    gravatar: db2e260f57e40ade7907bc303a295b70
    email: sebastien.vermeille@gmail.com
    web: https://cookiecode.dev/
    description: "Author of CookieCode, Clean Code principles supporter."

# Plugins
plugins:
  - octopress-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji
  - premonition
  - jekyll-time-to-read

gems:
  - octopress-paginate

#emoji:
# used to define a custom set of emojis
#  src: "/assets/images/emoji"

output_ext: ".html"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    category: "/categories/:name/"

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'source-code'
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

collections:
  oss:
    output: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

sass:
  sass_dir: _sass
  style: compressed

premonition:
  types:
    error:
      fa-icon: "fa-bug"
    question:
      fa-icon: "fa-question"

#Pagination
pagination:
  per_page: 2
  limit: false

#paginate:
#  collection:   posts
#  per_page:     2            # maximum number of items per page
#  limit:        false              # Maximum number of pages to paginate (false for unlimited)
#  permalink:    /page:num/     # pagination path (relative to template page)
#  title_suffix: " - page :num" # Append to template's page title
#  category:     ''             # Paginate items in this category
#  categories:   []             # Paginate items in any of these categories
#  tag:          ''             # Paginate items tagged with this tag
#  tags:         []             # Paginate items tagged with any of these tags
#  reversed:     false          # Reverse the order of the documents